[workspace]
members = [
    "crypto",
    "storage",
    "server",
    "network",
    "passmgr-cli",
    "passmgr-gui",
]
resolver = "2"

[workspace.dependencies]
bincode = "1.3"
dirs = "6.0"
serde = { version = "1", features = ["derive"] }
sled = "0.34"
thiserror = "2.0.6"