[package]
name = "storage"
version = "0.0.2"
edition = "2021"

[dependencies]
sled = "0.34.7"

bincode.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempdir = "0.3"