[package]
name = "storage"
version = "0.0.3"
edition = "2021"

[dependencies]
ciphers = { path = "../ciphers" }
sled = "0.34.7"

bincode.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempdir = "0.3"