[package]
name = "storage"
version = "0.0.1"
edition = "2021"

[dependencies]
bincode = "1.3.3"
directories = "5.0.1"
serde = { version = "1", features = ["derive"] }
sled = "0.34.7"
thiserror.workspace = true
