[package]
name = "storage"
version = "0.0.5"
edition = "2021"

[dependencies]
crypto = { path = "../crypto" }
sled = "0.34.7"
soft-aes = "0.2.0"

bincode.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempdir = "0.3"
rand = "0.8"
