[package]
name = "passmgr-cli"
version = "0.0.3"
edition = "2021"

[dependencies]
crypto = { path = "../crypto" }
storage = { path = "../storage" }
clap = { version = "4.4", features = ["derive"] }
rpassword = "7.0"

bincode.workspace = true
thiserror.workspace = true
