[package]
name = "passmgr-cli"
version = "0.0.3"
edition = "2021"

[dependencies]
ciphers = { path = "../ciphers" }
storage = { path = "../storage" }
clap = { version = "4.4", features = ["derive"] }

bincode = "1.3"
rpassword = "7.0"

thiserror.workspace = true